[package]
name = "mdns"
version = "0.1.5"
authors = ["Dylan McKay <dylanmckay34@gmail.com>"]

description = "A multicast DNS client"
license = "MIT"
documentation = "https://docs.rs/mdns"
repository = "https://github.com/dylanmckay/mdns"

keywords = ["mdns", "dns", "multicast", "chromecast"]

[dependencies]
mio = "0.6"
dns-parser = "0.6"
net2 = "0.2"
error-chain = "0.6"
ifaces = "0.0.3"
